Repository unisonweb/unison, pull requests merged in 2020-04, with the labels that each got.

#1401 implement `dependents <x>`, `dependencies <x>`, and `debug.file`
  parser-typechecker/src/Unison/Codebase/Branch.hs
  parser-typechecker/src/Unison/Codebase/Editor/HandleInput.hs
  parser-typechecker/src/Unison/Codebase/Editor/Input.hs
  parser-typechecker/src/Unison/Codebase/Editor/Output.hs
  parser-typechecker/src/Unison/Codebase/FileCodebase.hs
  parser-typechecker/src/Unison/CommandLine/InputPatterns.hs
  parser-typechecker/src/Unison/CommandLine/OutputMessages.hs
  parser-typechecker/src/Unison/NamePrinter.hs
  parser-typechecker/src/Unison/Util/Pretty.hs
  unison-core/src/Unison/LabeledDependency.hs
  unison-core/src/Unison/Referent.hs
  unison-src/transcripts/dependents-dependencies-debugfile.md
  unison-src/transcripts/dependents-dependencies-debugfile.output.md
Labels: ready-to-merge

#1345 Failing transcripts should always show the failing stanza
  parser-typechecker/src/Unison/Codebase/TranscriptParser.hs
  parser-typechecker/tests/Unison/Test/Transcripts.hs
  parser-typechecker/unison-parser-typechecker.cabal
  unison-src/transcripts/errors/ucm-hide-all-error.md
  unison-src/transcripts/errors/ucm-hide-all-error.output.md
  unison-src/transcripts/errors/ucm-hide-all.md
  unison-src/transcripts/errors/ucm-hide-all.output.md
  unison-src/transcripts/errors/ucm-hide-error.md
  unison-src/transcripts/errors/ucm-hide-error.output.md
  unison-src/transcripts/errors/ucm-hide.md
  unison-src/transcripts/errors/ucm-hide.output.md
  unison-src/transcripts/errors/unison-hide-all-error.md
  unison-src/transcripts/errors/unison-hide-all-error.output.md
  unison-src/transcripts/errors/unison-hide-all.md
  unison-src/transcripts/errors/unison-hide-all.output.md
  unison-src/transcripts/errors/unison-hide-error.md
  unison-src/transcripts/errors/unison-hide-error.output.md
  unison-src/transcripts/errors/unison-hide.md
  unison-src/transcripts/errors/unison-hide.output.md
Labels: ready-to-merge

#1405 Fix #1402: Only display watch message if there're watch expressions
  parser-typechecker/src/Unison/CommandLine/OutputMessages.hs
  unison-src/transcripts/addupdatemessages.output.md
  unison-src/transcripts/blocks.output.md
  unison-src/transcripts/check873.output.md
  unison-src/transcripts/deleteReplacements.output.md
  unison-src/transcripts/diff.output.md
  unison-src/transcripts/doc-formatting.output.md
  unison-src/transcripts/docs.output.md
  unison-src/transcripts/find-patch.output.md
  unison-src/transcripts/fix-big-list-crash.output.md
  unison-src/transcripts/fix1334.output.md
  unison-src/transcripts/fix1356.output.md
  unison-src/transcripts/fix849.output.md
  unison-src/transcripts/fix942.output.md
  unison-src/transcripts/fix987.output.md
  unison-src/transcripts/hello.output.md
  unison-src/transcripts/link.output.md
  unison-src/transcripts/mergeloop.output.md
  unison-src/transcripts/merges.output.md
  unison-src/transcripts/numbered-args.output.md
  unison-src/transcripts/propagate.output.md
  unison-src/transcripts/reflog.output.md
  unison-src/transcripts/resolve.output.md
  unison-src/transcripts/todo-bug-builtins.output.md
  unison-src/transcripts/transcript-parser-commands.output.md
Labels: ready-to-merge

#1407 Add a transcript testing the ambiguous metadata error
  unison-src/transcripts/ambiguous-metadata.md
  unison-src/transcripts/ambiguous-metadata.output.md
Labels: ready-to-merge

#1411 delay serializing IOSource definitions until `builtins.merge`
  parser-typechecker/src/Unison/Codebase.hs
  parser-typechecker/src/Unison/Codebase/Editor/HandleInput.hs
  parser-typechecker/src/Unison/Codebase/Editor/Input.hs
  parser-typechecker/src/Unison/Codebase/FileCodebase.hs
  parser-typechecker/src/Unison/Codebase/FileCodebase/Common.hs
  parser-typechecker/src/Unison/Codebase/FileCodebase/CopyFilterIndex.hs
  parser-typechecker/src/Unison/CommandLine/InputPatterns.hs
  parser-typechecker/src/Unison/Runtime/IOSource.hs
  unison-src/transcripts/alias-many.output.md
  unison-src/transcripts/builtins-merge.output.md
  unison-src/transcripts/create-author.md
  unison-src/transcripts/create-author.output.md
  unison-src/transcripts/diff.md
  unison-src/transcripts/emptyCodebase.md
  unison-src/transcripts/emptyCodebase.output.md
  unison-src/transcripts/link.md
  unison-src/transcripts/merges.output.md
  unison-src/transcripts/reflog.output.md
Labels: ready-to-merge

#1420 flushing some lint
  parser-typechecker/tests/Unison/Test/Codebase/FileCodebase.hs
  yaks/easytest/src/EasyTest.hs
Labels: ready-to-merge

#1419 just run `stack exec` once in `Transcripts.hs` and save the result
  parser-typechecker/transcripts/Transcripts.hs
Labels: ready-to-merge

#1422 fix pull regression in #1317
  parser-typechecker/src/Unison/Codebase/FileCodebase/Common.hs
Labels: ready-to-merge

#1424 Couple of fixes to whitespace handling in doc literals
  parser-typechecker/src/Unison/TermParser.hs
  unison-core/src/Unison/Util/List.hs
  unison-src/transcripts/doc-formatting.md
  unison-src/transcripts/doc-formatting.output.md
  unison-src/transcripts/docs.md
  unison-src/transcripts/docs.output.md
Labels: pretty-printer

#1444 introduce `unlessError` combinator
  parser-typechecker/src/Unison/Codebase/Editor/HandleInput.hs
Labels: ready-to-merge

#1451 Supress metadata noise
  parser-typechecker/src/Unison/Codebase/Editor/HandleInput.hs
  parser-typechecker/src/Unison/CommandLine/OutputMessages.hs
Labels: dx
