Repository unisonweb/unison, pull requests merged in 2021-12, with the labels that each got.

#2740 Add Debug.trace builtin
  parser-typechecker/src/Unison/Builtin.hs
  parser-typechecker/src/Unison/Runtime/ANF.hs
  parser-typechecker/src/Unison/Runtime/Builtin.hs
  parser-typechecker/src/Unison/Runtime/Interface.hs
  parser-typechecker/src/Unison/Runtime/MCode.hs
  parser-typechecker/src/Unison/Runtime/Machine.hs
  parser-typechecker/src/Unison/Runtime/Serialize.hs
  unison-src/transcripts/alias-many.output.md
  unison-src/transcripts/builtins-merge.output.md
  unison-src/transcripts/emptyCodebase.output.md
  unison-src/transcripts/merges.output.md
  unison-src/transcripts/reflog.output.md
  unison-src/transcripts/squash.output.md
Labels: ready-to-merge

#2731 Allow fork'ing/pulling/etc. over a branch with an empty HEAD.
  unison-cli/src/Unison/Codebase/Editor/HandleInput.hs
  unison-cli/tests/Unison/Test/GitSync.hs
  unison-src/transcripts/empty-namespaces.md
  unison-src/transcripts/empty-namespaces.output.md
Labels: ready-to-merge

#2713 pull.without-history - smaller pulls
  parser-typechecker/src/Unison/Codebase.hs
  parser-typechecker/src/Unison/Codebase/Branch.hs
  unison-cli/src/Unison/Codebase/Editor/Command.hs
  unison-cli/src/Unison/Codebase/Editor/HandleCommand.hs
  unison-cli/src/Unison/Codebase/Editor/HandleInput.hs
  unison-cli/src/Unison/Codebase/Editor/Input.hs
  unison-cli/src/Unison/Codebase/Editor/Output.hs
  unison-cli/src/Unison/CommandLine/InputPatterns.hs
  unison-cli/src/Unison/CommandLine/OutputMessages.hs
  unison-cli/src/Unison/CommandLine/Welcome.hs
Labels: ready-to-merge

#2747 Fix wrong hash being returned from squash pull
  parser-typechecker/src/Unison/Codebase.hs
  unison-cli/tests/Unison/Test/GitSync.hs
Labels: ready-to-merge

#2754 Fix a bunch of pretty-printer bugs
  parser-typechecker/src/Unison/TermPrinter.hs
  unison-src/transcripts-round-trip/main.md
  unison-src/transcripts-round-trip/main.output.md
  unison-src/transcripts/bug-strange-closure.output.md
Labels: pretty-printer, ready-to-merge

#2739 Kill forked threads when runtime evaluation completes.
  parser-typechecker/src/Unison/Runtime/Interface.hs
  parser-typechecker/src/Unison/Runtime/Machine.hs
  parser-typechecker/tests/Unison/Test/MCode.hs
  parser-typechecker/tests/Unison/Test/UnisonSources.hs
  unison-cli/src/Unison/Codebase/TranscriptParser.hs
  unison-cli/unison/Main.hs
Labels: runtime

#2734 Improve ctrl-c and sig INT catching in main UCM loop
  unison-cli/package.yaml
  unison-cli/src/Compat.hs
  unison-cli/src/Unison/CommandLine/Main.hs
  unison-cli/unison-cli.cabal
  unison-cli/unison/Compat.hs
  unison-cli/unison/Main.hs
Labels: codebase-manager

#2761 Allow moving branch (and its history!) over a deleted branch.
  unison-cli/src/Unison/Codebase/Editor/HandleInput.hs
  unison-src/transcripts/empty-namespaces.md
  unison-src/transcripts/empty-namespaces.output.md
Labels: codebase-manager

#2752 add a script to perform checks tests similar to CI
  scripts/check.sh
Labels: ready-to-merge
