Repository unisonweb/unison, pull requests merged in 2021-05, with the labels that each got.

#1907 Fix regression #1905 which disabled command line args to UCM
  parser-typechecker/src/Unison/Server/CodebaseServer.hs
Labels: ready-to-merge

#1908 Remove token auth from static portion of UI
  parser-typechecker/src/Unison/Server/CodebaseServer.hs
Labels: ready-to-merge

#1910 Fix some variable capture problems
  parser-typechecker/src/Unison/Runtime/ANF.hs
  parser-typechecker/src/Unison/Runtime/Pattern.hs
  unison-core/src/Unison/ABT.hs
  unison-src/tests/methodical/pattern-matching.u
  unison-src/tests/methodical/pattern-matching.ur
Labels: ready-to-merge

#1911 Fix a boolean in the new runtime
  parser-typechecker/src/Unison/Runtime/ANF.hs
  unison-src/transcripts-using-base/builtins.md
  unison-src/transcripts-using-base/builtins.output.md
Labels: ready-to-merge

#1913 Delete unused code only used by old runtime
  parser-typechecker/src/Unison/Runtime/ANF.hs
  parser-typechecker/src/Unison/Runtime/IR.hs
  parser-typechecker/unison-parser-typechecker.cabal
Labels: new-runtime, ready-to-merge

#1909 Stop using old `io.Mode` and `io.BufferMode` types in favor of versions in `io2` package
  parser-typechecker/src/Unison/Builtin/Decls.hs
  parser-typechecker/src/Unison/Runtime/ANF.hs
  parser-typechecker/src/Unison/Runtime/Builtin.hs
  parser-typechecker/src/Unison/Runtime/Foreign/Function.hs
  parser-typechecker/src/Unison/Runtime/IOSource.hs
  unison-src/transcripts-using-base/base.u
  unison-src/transcripts/emptyCodebase.output.md
  unison-src/transcripts/io.md
  unison-src/transcripts/io.output.md
Labels: ready-to-merge

#1917 fix a bug in watch syncing and in watch syncing summary
  codebase2/codebase-sqlite/U/Codebase/Sqlite/Branch/Format.hs
  codebase2/codebase-sqlite/U/Codebase/Sqlite/Patch/Format.hs
  codebase2/codebase-sqlite/U/Codebase/Sqlite/Serialization.hs
  codebase2/codebase-sqlite/U/Codebase/Sqlite/Sync22.hs
  codebase2/codebase-sqlite/U/Codebase/Sqlite/Term/Format.hs
  parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs
Labels: ready-to-merge

#1920 Move auth token from query string to resource path
  parser-typechecker/src/Unison/Server/CodebaseServer.hs
  parser-typechecker/src/Unison/Server/Endpoints/FuzzyFind.hs
  parser-typechecker/src/Unison/Server/Endpoints/GetDefinitions.hs
  parser-typechecker/src/Unison/Server/Endpoints/ListNamespace.hs
  parser-typechecker/unison/Main.hs
Labels: codebase-ui, ready-to-merge

#1925 Move `static` outside the auth token
  parser-typechecker/src/Unison/Server/CodebaseServer.hs
Labels: ready-to-merge

#1935 add gitsync22.*.lightweightPatch test
  parser-typechecker/tests/Unison/Test/GitSync.hs
Labels: ready-to-merge

#1937 Fix some pattern compilation issues
  parser-typechecker/src/Unison/Runtime/Pattern.hs
  unison-src/tests/methodical/abilities.u
  unison-src/tests/methodical/abilities.ur
  unison-src/transcripts/lambdacase.md
  unison-src/transcripts/lambdacase.output.md
Labels: ready-to-merge

#1945 Don't have two versions of Either.mapRight and List.map
  parser-typechecker/src/Unison/Runtime/IOSource.hs
  unison-src/transcripts-using-base/base.u
Labels: ready-to-merge

#1955 fix Sqlite.Queries.lca algorithm
  codebase2/codebase-sqlite/U/Codebase/Sqlite/Queries.hs
Labels: ready-to-merge

#1957 Fix some runtime problems
  parser-typechecker/src/Unison/Runtime/Decompile.hs
  parser-typechecker/src/Unison/Runtime/Interface.hs
  parser-typechecker/src/Unison/Runtime/Machine.hs
  unison-src/transcripts/bug-strange-closure.md
  unison-src/transcripts/bug-strange-closure.output.md
Labels: ready-to-merge

#1953 Use write-ahead-logging mode in sqlite
  codebase2/codebase-sqlite/U/Codebase/Sqlite/Queries.hs
Labels: ready-to-merge

#1964 add a version of `Branch.before` that can use a custom LCA implementation
  parser-typechecker/src/Unison/Codebase/Branch.hs
  parser-typechecker/src/Unison/Codebase/Causal.hs
  parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs
Labels: ready-to-merge

#1966 wrap SqliteCodebase.syncInternal in an immediate transaction
  codebase2/codebase-sqlite/U/Codebase/Sqlite/Queries.hs
  parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs
Labels: ready-to-merge

#1973 move Timing package to call it from v2 codebase internals
  codebase2/util/U/Util/Timing.hs
  codebase2/util/package.yaml
  codebase2/util/unison-util.cabal
  parser-typechecker/src/Unison/Codebase.hs
  parser-typechecker/src/Unison/Codebase/Editor/HandleInput.hs
  parser-typechecker/src/Unison/Codebase/FileCodebase.hs
  parser-typechecker/src/Unison/Codebase/FileCodebase/Common.hs
  parser-typechecker/src/Unison/Codebase/FileCodebase/SlimCopyRegenerateIndex.hs
  parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs
  parser-typechecker/unison-parser-typechecker.cabal
Labels: ready-to-merge

#1974 Inline simple `x = y` lets during compilation.
  parser-typechecker/src/Unison/Runtime/ANF.hs
  parser-typechecker/src/Unison/Runtime/Interface.hs
Labels: ready-to-merge

#1976 Add cycle length cache for 7.8x speedup loading branches
  codebase2/codebase-sqlite/U/Codebase/Sqlite/Sync22.hs
  codebase2/util/U/Util/Cache.hs
  parser-typechecker/src/Unison/Codebase/Branch.hs
  parser-typechecker/src/Unison/Codebase/Causal.hs
  parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs
Labels: ready-to-merge

#1978 slightly expanded timing logging
  codebase2/codebase-sqlite/U/Codebase/Sqlite/Operations.hs
  codebase2/codebase-sqlite/U/Codebase/Sqlite/Queries.hs
  parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs
Labels: ready-to-merge

#1980 Use codebase LCA for squash merges
  parser-typechecker/src/Unison/Codebase/Branch.hs
  parser-typechecker/src/Unison/Codebase/Causal.hs
  unison-src/transcripts/squash.md
  unison-src/transcripts/squash.output.md
Labels: ready-to-merge

#1981 Avoid calling `error` in the new runtime
  parser-typechecker/src/Unison/Runtime/ANF.hs
  parser-typechecker/src/Unison/Runtime/ANF/Serialize.hs
  parser-typechecker/src/Unison/Runtime/Exception.hs
  parser-typechecker/src/Unison/Runtime/Foreign/Function.hs
  parser-typechecker/src/Unison/Runtime/Interface.hs
  parser-typechecker/src/Unison/Runtime/MCode.hs
  parser-typechecker/src/Unison/Runtime/Pattern.hs
Labels: ready-to-merge

#1983 fix missing-deps calculation for syncing branches that only exist in memory
  parser-typechecker/src/Unison/Codebase/Editor/HandleInput.hs
  parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs
Labels: ready-to-merge

#1971 don't duplicate Safe.headMay
  codebase2/codebase-sqlite/U/Codebase/Sqlite/Queries.hs
  codebase2/codebase-sqlite/package.yaml
  codebase2/codebase-sqlite/unison-codebase-sqlite.cabal
Labels: ready-to-merge

#1993 Add missing TLS builtins
  parser-typechecker/src/Unison/Builtin.hs
  unison-src/transcripts/alias-many.output.md
  unison-src/transcripts/builtins-merge.output.md
  unison-src/transcripts/emptyCodebase.output.md
  unison-src/transcripts/merges.output.md
  unison-src/transcripts/reflog.output.md
  unison-src/transcripts/squash.output.md
Labels: ready-to-merge

#2002 Fix to `squash a b` to properly short circuit in the case where `b <= a`
  parser-typechecker/src/Unison/Codebase/Branch.hs
  parser-typechecker/src/Unison/Codebase/Causal.hs
  parser-typechecker/src/Unison/Codebase/Editor/Output.hs
  parser-typechecker/tests/Unison/Test/Codebase/Causal.hs
  unison-src/transcripts/fix1926.output.md
  unison-src/transcripts/fix2000.md
  unison-src/transcripts/fix2000.output.md
  unison-src/transcripts/squash.output.md
Labels: ready-to-merge

#2010 Fix to pretty-printing of
  parser-typechecker/src/Unison/TermPrinter.hs
  unison-src/transcripts-using-base/doc.md.files/syntax.u
  unison-src/transcripts-using-base/doc.output.md
  unison-src/transcripts/bug-strange-closure.output.md
Labels: ready-to-merge

#1996 Speed up `push` by using fast SQL-based `Branch.before` calculation
  codebase2/codebase-sqlite/U/Codebase/Sqlite/Operations.hs
  codebase2/codebase-sqlite/U/Codebase/Sqlite/Queries.hs
  parser-typechecker/src/Unison/Codebase.hs
  parser-typechecker/src/Unison/Codebase/Branch.hs
  parser-typechecker/src/Unison/Codebase/Editor/HandleInput.hs
  parser-typechecker/src/Unison/Codebase/FileCodebase.hs
  parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs
  parser-typechecker/tests/Unison/Test/GitSync.hs
Labels: ready-to-merge

#2016 Minor nit: don't show the API url unless launching UCM in headless mode
  parser-typechecker/unison/Main.hs
Labels: ready-to-merge

#2033 Fix bad failure references in builtins
  parser-typechecker/src/Unison/Builtin/Decls.hs
  parser-typechecker/src/Unison/Runtime/Builtin.hs
  parser-typechecker/src/Unison/Runtime/IOSource.hs
  unison-src/transcripts-using-base/fix2027.md
  unison-src/transcripts-using-base/fix2027.output.md
Labels: ready-to-merge

#2030 Fix wrapper code for putBytes
  parser-typechecker/src/Unison/Runtime/Builtin.hs
  parser-typechecker/src/Unison/Runtime/Decompile.hs
  unison-src/transcripts/fix2026.md
  unison-src/transcripts/fix2026.output.md
Labels: ready-to-merge

#2035 add `_edits` to `Branch0` hash calculation
  parser-typechecker/src/Unison/Codebase/Branch.hs
  parser-typechecker/tests/Suite.hs
  parser-typechecker/tests/Unison/Test/Codebase/Upgrade12.hs
  parser-typechecker/tests/Unison/Test/Git.hs
  parser-typechecker/tests/Unison/Test/GitSync.hs
  parser-typechecker/unison-parser-typechecker.cabal
  unison-src/transcripts/fix-1381-excess-propagate.output.md
  unison-src/transcripts/fix2000.md
  unison-src/transcripts/fix2000.output.md
  unison-src/transcripts/link.output.md
  unison-src/transcripts/mergeloop.output.md
  unison-src/transcripts/merges.output.md
  unison-src/transcripts/reflog.output.md
  unison-src/transcripts/squash.output.md
Labels: ready-to-merge

#2036 Update mergify.yml to work with new build matrix
  .mergify.yml
Labels: ready-to-merge
