Repository unisonweb/unison, pull requests merged in 2021-07, with the labels that each got.

#2170 Avoid building the complete FQN mapping when only a few keys are needed
  parser-typechecker/src/Unison/Server/Backend.hs
Labels: ready-to-merge

#2179 Avoid rebuilding term and type relations on each call to fuzzy find
  unison-core/src/Unison/Names2.hs
Labels: ready-to-merge

#2182 Fix bad calling convention for `Value.load`
  parser-typechecker/src/Unison/Runtime/Foreign.hs
  parser-typechecker/src/Unison/Runtime/Foreign/Function.hs
  parser-typechecker/src/Unison/Runtime/Machine.hs
  unison-src/transcripts-using-base/codeops.md
  unison-src/transcripts-using-base/codeops.output.md
Labels: ready-to-merge

#2191 Delete 9 files with namespace blocks.
  unison-src/Cofree.u
  unison-src/EasyTest.u
  unison-src/Trie.u
  unison-src/WeightedSearch.u
  unison-src/errors/console.u
  unison-src/errors/console2.u
  unison-src/errors/map-reduce.u
  unison-src/errors/poor-error-message/consoleh.u
  unison-src/sheepshead.u
Labels: ready-to-merge

#2226 Fix division and modulus for Nat
  parser-typechecker/src/Unison/Runtime/MCode.hs
  parser-typechecker/src/Unison/Runtime/Machine.hs
Labels: ready-to-merge

#2233 Test `Nat./` and `Nat.mod`
  unison-src/transcripts-using-base/builtins.md
  unison-src/transcripts-using-base/builtins.output.md
Labels: ready-to-merge

#2116 Add docs to `getDefinition` endpoint
  parser-typechecker/src/Unison/Builtin.hs
  parser-typechecker/src/Unison/Builtin/Decls.hs
  parser-typechecker/src/Unison/Codebase.hs
  parser-typechecker/src/Unison/Codebase/Editor/DisplayObject.hs
  parser-typechecker/src/Unison/Codebase/Editor/HandleInput.hs
  parser-typechecker/src/Unison/Codebase/Editor/Output.hs
  parser-typechecker/src/Unison/Codebase/Editor/TodoOutput.hs
  parser-typechecker/src/Unison/CommandLine/DisplayValues.hs
  parser-typechecker/src/Unison/CommandLine/Main.hs
  parser-typechecker/src/Unison/CommandLine/OutputMessages.hs
  parser-typechecker/src/Unison/Runtime/IOSource.hs
  parser-typechecker/src/Unison/Server/Backend.hs
  parser-typechecker/src/Unison/Server/CodebaseServer.hs
  parser-typechecker/src/Unison/Server/Doc.hs
  parser-typechecker/src/Unison/Server/Endpoints/FuzzyFind.hs
  parser-typechecker/src/Unison/Server/Endpoints/GetDefinitions.hs
  parser-typechecker/src/Unison/Server/SearchResult'.hs
  parser-typechecker/src/Unison/Server/Types.hs
  parser-typechecker/src/Unison/TermPrinter.hs
  parser-typechecker/src/Unison/TypePrinter.hs
  parser-typechecker/src/Unison/Util/SyntaxText.hs
  parser-typechecker/unison-parser-typechecker.cabal
  parser-typechecker/unison/Main.hs
  unison-core/src/Unison/HashQualified'.hs
  unison-src/transcripts/suffixes.output.md
Labels: C3, E4, I3, P1, R3, codebase-server, ready-to-merge

#2250 Allow multiple guards to be attached to a case a `cases` or `match` expression
  .github/workflows/ci.yaml
  parser-typechecker/src/Unison/Runtime/Pattern.hs
  parser-typechecker/src/Unison/TermParser.hs
  parser-typechecker/src/Unison/TermPrinter.hs
  parser-typechecker/src/Unison/Typechecker/Context.hs
  unison-core/src/Unison/ABT.hs
  unison-src/tests/pattern-matching.u
  unison-src/tests/pattern-matching.ur
  unison-src/transcripts/lambdacase.md
  unison-src/transcripts/lambdacase.output.md
Labels: parser, pretty-printer

#2029 Allow `Exception` ability to be used by main functions
  parser-typechecker/src/Unison/Builtin/Decls.hs
  parser-typechecker/src/Unison/Codebase/Editor/HandleInput.hs
  parser-typechecker/src/Unison/Codebase/MainTerm.hs
  parser-typechecker/src/Unison/Runtime/Builtin.hs
  parser-typechecker/src/Unison/Runtime/Decompile.hs
  parser-typechecker/src/Unison/Runtime/Interface.hs
  parser-typechecker/src/Unison/Runtime/Machine.hs
  unison-src/transcripts/alias-many.output.md
  unison-src/transcripts/builtins-merge.output.md
  unison-src/transcripts/emptyCodebase.output.md
  unison-src/transcripts/fix1800.output.md
  unison-src/transcripts/fix2026.output.md
  unison-src/transcripts/merges.output.md
  unison-src/transcripts/reflog.output.md
  unison-src/transcripts/squash.output.md
  unison-src/transcripts/top-level-exceptions.md
  unison-src/transcripts/top-level-exceptions.output.md
Labels: C2, E4, I2, P1, R3, in progress

#1999 Add getLine I/O builtin
  parser-typechecker/src/Unison/Builtin.hs
  parser-typechecker/src/Unison/Runtime/Builtin.hs
  unison-src/transcripts-using-base/base.u
  unison-src/transcripts/alias-many.output.md
  unison-src/transcripts/builtins-merge.output.md
  unison-src/transcripts/emptyCodebase.output.md
  unison-src/transcripts/io.md
  unison-src/transcripts/io.output.md
  unison-src/transcripts/merges.output.md
  unison-src/transcripts/reflog.output.md
  unison-src/transcripts/squash.output.md
Labels: C3, E1, I1, R3, ready-to-merge

#2272 Fix #2261
  parser-typechecker/src/Unison/Server/Doc.hs
Labels: ready-to-merge

#2259 Allow constructor replacement during update propagation
  parser-typechecker/src/Unison/Codebase/Editor/HandleInput.hs
  parser-typechecker/src/Unison/Codebase/Editor/Output.hs
  parser-typechecker/src/Unison/Codebase/Editor/Propagate.hs
  parser-typechecker/src/Unison/Util/Star3.hs
  parser-typechecker/tests/Unison/Test/GitSync.hs
  unison-core/src/Unison/Pattern.hs
  unison-core/src/Unison/Term.hs
  unison-src/transcripts/command-replace.md
  unison-src/transcripts/command-replace.output.md
  unison-src/transcripts/deleteReplacements.md
  unison-src/transcripts/deleteReplacements.output.md
  unison-src/transcripts/fix2254.md
  unison-src/transcripts/fix2254.output.md
  unison-src/transcripts/resolve.md
  unison-src/transcripts/resolve.output.md
Labels: ready-to-merge

#2279 Syntax: Replace Constructor + Request with Referent
  parser-typechecker/src/Unison/DeclPrinter.hs
  parser-typechecker/src/Unison/Server/Syntax.hs
  parser-typechecker/src/Unison/TermPrinter.hs
  parser-typechecker/src/Unison/Util/ColorText.hs
  parser-typechecker/src/Unison/Util/SyntaxText.hs
Labels: ready-to-merge
