Repository unisonweb/unison, pull requests merged in 2022-10, with the labels that each got.

#3472 Term/Type Summary API tweaks
  parser-typechecker/src/Unison/Runtime/Builtin.hs
  unison-core/src/Unison/Reference.hs
  unison-core/src/Unison/Referent.hs
  unison-share-api/src/Unison/Server/Backend.hs
  unison-share-api/src/Unison/Server/CodebaseServer.hs
  unison-share-api/src/Unison/Server/Endpoints/DefinitionSummary.hs
  unison-share-api/src/Unison/Server/Endpoints/GetDefinitions.hs
  unison-share-api/src/Unison/Server/Orphans.hs
  unison-src/transcripts/api-summaries.md
  unison-src/transcripts/api-summaries.output.md
Labels: ready-to-merge

#3498 Fixed the code of the fromBase64UrlEncoded
  parser-typechecker/src/Unison/Runtime/Builtin.hs
  unison-src/transcripts-using-base/base.u
  unison-src/transcripts/builtins.md
  unison-src/transcripts/builtins.output.md
Labels: ready-to-merge

#3507 Fix pretty-printing of empty docs
  parser-typechecker/src/Unison/Runtime/IOSource.hs
  unison-cli/src/Unison/CommandLine/DisplayValues.hs
Labels: codebase-manager, pretty-printer, documentation, ready-to-merge

#3511 Fix roundtrip error with lambda as a final argument, which ignores its own argument
  parser-typechecker/src/Unison/Syntax/TermPrinter.hs
  parser-typechecker/tests/Unison/Test/Syntax/TermPrinter.hs
  unison-src/transcripts-round-trip/main.md
  unison-src/transcripts-round-trip/main.output.md
  unison-src/transcripts/bug-strange-closure.output.md
  unison-src/transcripts/fix3171.output.md
  unison-src/transcripts/merge.output.md
Labels: pretty-printer, ready-to-merge

#3540 Fix to `Pattern.or` and `Pattern.replicate` to properly do backtracking when given composite patterns
  parser-typechecker/src/Unison/Util/Text/Pattern.hs
  parser-typechecker/tests/Unison/Test/Util/Text.hs
  unison-src/transcripts/builtins.md
  unison-src/transcripts/builtins.output.md
Labels: ready-to-merge

#2789 Do TDNR substitutions in a single term traversal
  parser-typechecker/src/Unison/FileParsers.hs
Labels: ready-to-merge

#3543 Fix universal quantifiers disappearing in nested bindings
  codebase2/util/src/U/Util/Monoid.hs
  lib/unison-pretty-printer/src/Unison/Util/Pretty.hs
  parser-typechecker/src/Unison/PrettyPrintEnv/MonadPretty.hs
  parser-typechecker/src/Unison/Syntax/DeclPrinter.hs
  parser-typechecker/src/Unison/Syntax/TermPrinter.hs
  parser-typechecker/src/Unison/Syntax/TypePrinter.hs
  parser-typechecker/tests/Unison/Test/Syntax/TermPrinter.hs
  parser-typechecker/tests/Unison/Test/Syntax/TypePrinter.hs
  parser-typechecker/unison-parser-typechecker.cabal
  unison-cli/src/Unison/CommandLine/DisplayValues.hs
  unison-cli/src/Unison/CommandLine/OutputMessages.hs
  unison-share-api/src/Unison/Server/Backend.hs
  unison-share-api/src/Unison/Server/Doc.hs
Labels: ready-to-merge

#3548 Comment out builtins from the edit command
  unison-cli/src/Unison/CommandLine/OutputMessages.hs
  unison-src/transcripts-round-trip/main.md
  unison-src/transcripts-round-trip/main.output.md
Labels: pretty-printer, ready-to-merge
