Repository unisonweb/unison, pull requests merged in 2022-03, with the labels that each got.

#2959 Enable completion for compile.output
  unison-cli/src/Unison/CommandLine/InputPatterns.hs
Labels: codebase-manager

#2960 Use softhang if a delayed block is the last argument to a function
  parser-typechecker/src/Unison/TermPrinter.hs
  unison-src/transcripts-round-trip/main.md
  unison-src/transcripts-round-trip/main.output.md
Labels: ready-to-merge

#2964 Re-arrange Migrations module to support multiple migrations.
  parser-typechecker/src/Unison/Codebase/Init/OpenCodebaseError.hs
  parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs
  parser-typechecker/src/Unison/Codebase/SqliteCodebase/Migrations.hs
  parser-typechecker/src/Unison/Codebase/SqliteCodebase/Migrations/MigrateSchema1To2.hs
  parser-typechecker/src/Unison/Codebase/SqliteCodebase/Migrations/MigrateSchema1To2/DbHelpers.hs
  parser-typechecker/src/Unison/Codebase/SqliteCodebase/Paths.hs
  parser-typechecker/src/Unison/Codebase/Type.hs
  parser-typechecker/unison-parser-typechecker.cabal
Labels: ready-to-merge

#2965 Rename compile.output to compile
  unison-cli/integration-tests/IntegrationTests/transcript.md
  unison-cli/integration-tests/IntegrationTests/transcript.output.md
  unison-cli/src/Unison/Codebase/Editor/HandleInput.hs
  unison-cli/src/Unison/CommandLine/InputPatterns.hs
  unison-cli/unison/Main.hs
Labels: ready-to-merge

#2973 updating website url references to new website
  development.markdown
  docs/type-declarations.markdown
  parser-typechecker/src/Unison/PrintError.hs
  parser-typechecker/src/Unison/Runtime/IOSource.hs
  unison-cli/src/Unison/CommandLine/Welcome.hs
  unison-src/transcripts-using-base/fix2297.output.md
  unison-src/transcripts/fix1696.output.md
  unison-src/transcripts/type-modifier-required.output.md
  yaks/easytest/easytest.cabal
Labels: ready-to-merge

#2976 Fix broken windows release automation
  .github/workflows/release.yaml
Labels: windows

#2982 Split off pretty-printer package
  lib/unison-pretty-printer/LICENSE
  lib/unison-pretty-printer/package.yaml
  lib/unison-pretty-printer/prettyprintdemo/Main.hs
  lib/unison-pretty-printer/src/Unison/Lexer/Pos.hs
  lib/unison-pretty-printer/src/Unison/PrettyTerminal.hs
  lib/unison-pretty-printer/src/Unison/Util/AnnotatedText.hs
  lib/unison-pretty-printer/src/Unison/Util/ColorText.hs
  lib/unison-pretty-printer/src/Unison/Util/Less.hs
  lib/unison-pretty-printer/src/Unison/Util/Pretty.hs
  lib/unison-pretty-printer/src/Unison/Util/Range.hs
  lib/unison-pretty-printer/src/Unison/Util/SyntaxText.hs
  lib/unison-pretty-printer/tests/Suite.hs
  lib/unison-pretty-printer/tests/Unison/Test/ColorText.hs
  lib/unison-pretty-printer/tests/Unison/Test/Range.hs
  lib/unison-pretty-printer/tests/Unison/Test/Util/Pretty.hs
  lib/unison-pretty-printer/unison-pretty-printer.cabal
  parser-typechecker/package.yaml
  parser-typechecker/tests/Suite.hs
  parser-typechecker/unison-parser-typechecker.cabal
  stack.yaml
  unison-cli/package.yaml
  unison-cli/unison-cli.cabal
Labels: ready-to-merge

#3019 Use a faster copy function in `arrayToChunk`
  parser-typechecker/src/Unison/Util/Bytes.hs
Labels: ready-to-merge
