Repository unisonweb/unison, pull requests merged in 2022-11, with the labels that each got.

#3570 lazy version of more direct implementation of deepTerms
  parser-typechecker/src/Unison/Codebase/Branch.hs
  parser-typechecker/src/Unison/Codebase/Branch/Type.hs
  parser-typechecker/src/Unison/Codebase/Metadata.hs
  unison-cli/src/Unison/Codebase/Editor/HandleInput.hs
  unison-cli/src/Unison/Codebase/Editor/Output.hs
  unison-src/transcripts/deep-names.md
  unison-src/transcripts/deep-names.output.md
  unison-src/transcripts/find-command.md
Labels: ready-to-merge

#3586 Add configuration docs
  README.md
  docs/configuration.md
Labels: ready-to-merge

#3628 Indent after newline in pattern lists
  parser-typechecker/src/Unison/Syntax/TermPrinter.hs
  unison-src/transcripts-round-trip/main.md
  unison-src/transcripts-round-trip/main.output.md
Labels: ready-to-merge, roundtrip-bug

#3634 Eta-reduce Doc term links to undo compiler expansion
  unison-cli/src/Unison/CommandLine/DisplayValues.hs
  unison-share-api/src/Unison/Server/Doc.hs
  unison-src/transcripts/fix3634.md
  unison-src/transcripts/fix3634.output.md
Labels: pretty-printer

#3629 Cleanup: delete prelude-extras package
  parser-typechecker/package.yaml
  parser-typechecker/unison-parser-typechecker.cabal
  stack.yaml
  stack.yaml.lock
  unison-core/package.yaml
  unison-core/src/Unison/DataDeclaration.hs
  unison-core/src/Unison/Term.hs
  unison-core/src/Unison/Type.hs
  unison-core/unison-core1.cabal
Labels: ready-to-merge

#3619 Fix codebase root branch cache bugs
  parser-typechecker/package.yaml
  parser-typechecker/src/Unison/Codebase/Init.hs
  parser-typechecker/src/Unison/Codebase/Init/OpenCodebaseError.hs
  parser-typechecker/src/Unison/Codebase/RootBranchCache.hs
  parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs
  parser-typechecker/src/Unison/Codebase/SqliteCodebase/GitError.hs
  parser-typechecker/src/Unison/Codebase/SqliteCodebase/Operations.hs
  parser-typechecker/src/Unison/Codebase/SqliteCodebase/Paths.hs
  parser-typechecker/src/Unison/Codebase/Type.hs
  parser-typechecker/tests/Unison/Test/CodebaseInit.hs
  parser-typechecker/unison-parser-typechecker.cabal
  unison-cli/src/Unison/CommandLine/OutputMessages.hs
  unison-cli/tests/Unison/Test/Ucm.hs
  unison-cli/transcripts/Transcripts.hs
  unison-cli/unison/Main.hs
Labels: ready-to-merge
