Repository unisonweb/unison, pull requests merged in 2022-02, with the labels that each got.

#2857 Fix: '"" should be parsed as delayed text
  CONTRIBUTORS.markdown
  parser-typechecker/src/Unison/Lexer.hs
  parser-typechecker/tests/Unison/Test/Lexer.hs
Labels: ready-to-merge

#2880 Use correct content when rendering docs as html
  parser-typechecker/src/Unison/Server/Doc/AsHtml.hs
Labels: ready-to-merge

#2887 doc.to-html: don't ignore callout emojis
  parser-typechecker/src/Unison/Server/Doc/AsHtml.hs
Labels: ready-to-merge

#2852 Fix incorrect keyword lexing in links in docs
  parser-typechecker/src/Unison/Lexer.hs
  unison-src/transcripts/doc-type-link-keywords.md
  unison-src/transcripts/doc-type-link-keywords.output.md
Labels: ready-to-merge

#2883 Add numbered output to `todo`
  unison-cli/src/Unison/Codebase/Editor/HandleInput.hs
  unison-cli/src/Unison/Codebase/Editor/Output.hs
  unison-cli/src/Unison/CommandLine/OutputMessages.hs
  unison-src/transcripts/resolve.md
  unison-src/transcripts/resolve.output.md
  unison-src/transcripts/todo.md
  unison-src/transcripts/todo.output.md
Labels: ready-to-merge

#2907 Fix an issue with the effect variable linearizing patch
  parser-typechecker/src/Unison/Typechecker/Context.hs
  unison-src/transcripts/abilities.md
  unison-src/transcripts/abilities.output.md
Labels: ready-to-merge

#2921 use posix paths when matching `git status` output
  parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs
Labels: ready-to-merge

#2929 Fix universal equality
  parser-typechecker/src/Unison/Runtime/Machine.hs
  unison-src/transcripts/builtins.md
  unison-src/transcripts/builtins.output.md
Labels: ready-to-merge

#2937 replace `removeDirectoryRecursive` with `removePathForcibly`
  unison-cli/integration-tests/IntegrationTests/ArgumentParsing.hs
  unison-cli/tests/Unison/Test/GitSync.hs
Labels: windows

#2938 codepage 65001 for parser-typechecker tests too
  lib/unison-util-relation/benchmarks/relation/Main.hs
  lib/unison-util-relation/package.yaml
  lib/unison-util-relation/test/Main.hs
  lib/unison-util-relation/unison-util-relation.cabal
  parser-typechecker/package.yaml
  parser-typechecker/tests/Suite.hs
  parser-typechecker/unison-parser-typechecker.cabal
  unison-cli/integration-tests/Suite.hs
  unison-cli/package.yaml
  unison-cli/transcripts/Transcripts.hs
  unison-cli/unison-cli.cabal
Labels: windows

#2949 Handle more inconsistencies with newline conversion on Windows
  lib/unison-prelude/src/Unison/Prelude.hs
  parser-typechecker/src/Unison/Codebase/Watch.hs
  parser-typechecker/src/Unison/Lexer.hs
  parser-typechecker/tests/Unison/Test/UnisonSources.hs
  unison-cli/tests/Unison/Test/GitSync.hs
  unison-src/parser-tests/GenerateErrors.hs
Labels: ready-to-merge, windows
